// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEtXkrZZFfvq2plNET56nRkdLAnq3jTIE',
    appId: '1:2292987104:web:8ded1442cea81b3e4b0c85',
    messagingSenderId: '2292987104',
    projectId: 'flora-dan-fauna',
    authDomain: 'flora-dan-fauna.firebaseapp.com',
    databaseURL: 'https://flora-dan-fauna-default-rtdb.firebaseio.com',
    storageBucket: 'flora-dan-fauna.appspot.com',
    measurementId: 'G-WV4HPK8RBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz9oSB3fSZ6K-2iLCpNewxq4ZJzomsTA4',
    appId: '1:2292987104:android:9961a5693515b6564b0c85',
    messagingSenderId: '2292987104',
    projectId: 'flora-dan-fauna',
    databaseURL: 'https://flora-dan-fauna-default-rtdb.firebaseio.com',
    storageBucket: 'flora-dan-fauna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsUjqgMq9o_8g_y00g8gMXcneWge7rgBw',
    appId: '1:2292987104:ios:ca7ed7a2e202995f4b0c85',
    messagingSenderId: '2292987104',
    projectId: 'flora-dan-fauna',
    databaseURL: 'https://flora-dan-fauna-default-rtdb.firebaseio.com',
    storageBucket: 'flora-dan-fauna.appspot.com',
    iosClientId: '2292987104-c427ebf6t3hb94krujekm8ta37ou7lu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.edugame',
  );
}
